apiVersion: v2
name: auth-o-tron
description: Auth-o-tron Helm charts
type: application

dependencies:
  - name: mongodb
    version: 15.6.x
    repository: "@bitnami"
    condition: mongodb.enabled

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
# It is recommended to use it with quotes.
appVersion: "0.1.0"