apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "fullname" .) | quote }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- include "auth-o-tron.renderConfig" . | nindent 4 }}