apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations: {{ include "auth-o-tron.podAnnotations" . | nindent 8 }}
    spec:
      imagePullSecrets: {{ include "auth-o-tron.imagePullSecrets" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: {{ include "auth-o-tron.containerPorts" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http-auth
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http-auth
            initialDelaySeconds: 3
            periodSeconds: 5
          env: {{ include "auth-o-tron.environment" . | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: config-volume
          configMap:
            name: {{ printf "%s-config" (include "fullname" .) | quote }}
            items:
              - key: config.yaml
                path: config.yaml
