{{- /* Define the named template outside any control structure */ -}}
{{- define "imagePullSecret" -}}
  {{- with .Values.pullSecret.imageCredentials -}}
    {{- printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .registry (printf "%s:%s" .username .password | b64enc) | b64enc -}}
  {{- end -}}
{{- end -}}

{{- /* Only render the Secret if pullSecret is enabled */ -}}
{{- if .Values.pullSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
