apiVersion: v1
kind: Service
metadata:
  name: auth-o-tron-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "fullname" . }}