{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.metrics.additionalLabels }}
    {{- toYaml .Values.metrics.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  # Select the service to monitor based on labels
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fullname" . }}
  
  # Define the endpoints to scrape
  endpoints:
    - port: http  # This should match the port name of the service
      path: /metrics
      interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
{{- end }}
