apiVersion: v1
kind: Service
metadata:
  name: auth-o-tron-svc
  labels:
    app.kubernetes.io/name: {{ include "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-auth
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "fullname" . }}